---
title: "Rezepte"
format: html
editor: visual

---


# Dies ist eine Uebersicht von Rezepten

## MEZZE

**Portionen:**
    6
    
**Zubereitungszeit:**
    1 Stunde 
    



**Zutaten:**

**Für die Auberginencreme:**

    2 Auberginen
    etwas Salz
    2 Knoblauchzehen
    0,5 Zitrone
    1 EL Olivenöl

**Für die Linsencreme:**

    1 kleine Zwiebel
    1 TL Olivenöl
    0,5 TL Kreuzkümmel (gemahlen)
    0,5 Kurkuma (gemahlen)
    400 ml Gemüsebrühe
    200 g rote Linsen
    etwas Salz
    1 EL Tahina (Sesampaste; aus dem Glas)
    1 EL Sesam

**Für den orientalischer Möhrensalat:**

    3 Möhren
    2 EL Olivenöl
    etwas Salz
    etwas Zucker
    0,5 TL Kreuzkümmel (gemahlen)
    10 Mandeln
    3 Stängel Minze

**Für den Tomatensalat:**

    2 Tomaten
    1 TL Schwarzkümmel
    etwas Salz
    etwas Zucker
    2 EL Olivenöl

**Für den Joghurt-Dip:**

    0,5 Salatgurke
    etwas Salz
    1 Knoblauchzehe
    1 EL Rosinen
    0,5 Bund Dill
    250 g griechischer Joghurt
    etwas Zucker

**Für die marinierte Oliven:**

    20 grüne Oliven
    1 Bio-Zitrone
    1 Knoblauchzehe
    1 EL Olivenöl

**Für den marinierten Schafskäse:**

    4 Stängel Koriander
    200 g Schafskäse( am besten türkischer Weißkäse)
    0,5 TL Sumach
    1 EL Olivenöl

**Zusätzlich:**

    1 Fladenbrot

* **Zubereitung:**

+ 1. Für die Auberginencreme den Backofen auf 230 Grad Ober- und Unterhitze vorheizen.

+ 2. Die Auberginen waschen, putzen, längs halbieren, auf der Schnittfläche einritzen und salzen.

+ 3. Auberginenhälften in eine Auflaufform oder auf ein Backblech geben und im vorheizten Ofen ca. 25 Minuten weich garen.

+ 4. Knoblauch schälen. Von der Zitrone den Saft auspressen.

+ 5. Das Fruchtfleisch aus den gegarten Auberginen herauskratzen. Auberginenfruchtfleisch und Knoblauch fein hacken. Olivenöl untermischen und mit Zitronensaft und Salz abschmecken.

+ 6. Für die Linsencreme die Zwiebel schälen und fein würfeln.

+ 7. In einem Topf Olivenöl erhitzen und die Zwiebeln darin andünsten. Kreuzkümmel und Kurkuma zugeben und die Brühe angießen. Die Linsen dazu geben und weich kochen.

+ 8. Weich gekochte Linsen mit Salz abschmecken. Dann die Linsen auf einem Sieb abtropfen, anschließend pürieren. Linsencreme mit Tahina abschmecken und mit Sesam bestreuen.

+ 9. Für den Möhrensalat die Möhren waschen, schälen, dann fein schneiden.

+ 10. In einer Pfanne Olivenöl erhitzen, die fein geschnittenen Möhren zugeben. Mit Salz, Zucker und Kreuzkümmel würzen und die Möhren weich dünsten.

+ 11. In der Zwischenzeit in einer zweiten Pfanne ohne Fett die Mandeln rösten, anschließend hacken.

+ 12. Die Minze abbrausen, trocken schütteln, die Blättchen abzupfen und fein schneiden.

+ 13. Die gedünsteten Möhren aus der Pfanne nehmen, Minze und Mandeln daruntermischen. Nochmals abschmecken.

+ 14. Für den Tomatensalat die Tomaten am Stielansatz einritzen, kurz in kochendes Wasser tauchen, herausnehmen und die Schale abziehen. Tomaten dann vierteln und die Kerne entfernen. Tomatenviertel fein würfeln.

+ 15. Schwarzkümmel mit einer Prise Salz und Zucker mörsern. Die Gewürzmischung zu den Tomaten geben, Olivenöl hinzufügen, alles vermischen und abschmecken.

+ 16. Für den Joghurt-Dip die Gurke abwaschen, dann raspeln. Gurkenraspel mit Salz würzen und 5 Minuten ziehen lassen.

+ 17. Knoblauch schälen und sehr fein hacken oder pürieren. Die Rosinen grob hacken.

+ 18. Dill abbrausen, trocken schütteln und fein schneiden.

+ 19. Die Gurkenraspel ausdrücken und zum Joghurt geben. Ebenfalls Knoblauch, Dill und Rosinen zugeben und alles vermischen. Mit Salz und Zucker abschmecken.

+ 20. Für die marinierten Oliven die Oliven abspülen und abtropfen lassen. Zitrone heiß abwaschen, abtrocknen, etwas Schale abreiben und den Saft auspressen. Knoblauch schälen und sehr fein hacken.

+ 21. Die Oliven in eine Schüssel geben, Zitronenabrieb und -saft, Knoblauch und Olivenöl zugeben und alles vermischen.

+ Tipp: Diese Mischung in einer feuerfesten Form bei 180 Grad im Backofen 5 Minuten ziehen lassen, dann schmeckt es noch besser.

+ 22. Für den marinierten Schafskäse Koriander abbrausen, trocken schütteln, die Blättchen abzupfen und fein schneiden.

+ 23. Käse zerbröseln, mit Sumach, Koriander und Olivenöl mischen.

+ 24. Die Mezze separat in kleine Schälchen füllen und auf eine Platte geben. Dazu Fladenbrot reichen.